### ISSUE TITLE
Tentacle does not play nicely with GitHub Enterprise which does not contain rate limiting headers

### ISSUE THREAD

**Issue by jgraves** [mdiep/Tentacle#24]
The initializer on the Response object explicitly unwraps the rate limiting header fields. However, these fields do not exist when using a GitHub Enterprise instance and Tentacle crashes when trying to unwrap them.

Here's the offending code:
`internal init(headerFields: [String : String]) {
        self.rateLimitRemaining = UInt(headerFields["X-RateLimit-Remaining"]!)!
        self.rateLimitReset = NSDate(timeIntervalSince1970: NSTimeInterval(headerFields["X-RateLimit-Reset"]!)!)
        self.links = linksInLinkHeader(headerFields["Link"] ?? "")
    }`

I'm not sure if Tentacle explicitly supports GitHub Enterprise, but I thought I'd leave this here just in case :). I'd be happy to submit a patch.

**Comment by mdiep** [comment]
Thanks for investigating this! I don't have access to a GitHub Enterprise instance, so I don't have a way to test this.

A patch would be great! It sounds like both those fields should be `Optional`s. Otherwise, I should be able to do it tonight. A test fixture would be especially helpful.

**Comment by jgraves** [comment]
done and done :)

**Comment by mdiep** [comment]
Fixed by #26.
