### ISSUE TITLE
Swift 4 Release

### ISSUE THREAD

**Issue by dcaunt** [mdiep/Tentacle#90]
We should probably cut a new release since the Swift 4 work is merged.

I'm happy to draft a release but @Palleas might want to do it seeing as he did most of the work 😄

**Comment by Palleas** [comment]
I won't have the time to do it properly before next week, happy to let you do it and learn how it's done! 😄

**Comment by dcaunt** [comment]
There's not much to it 😉  I've drafted a release for @mdiep to take a look at.

**Comment by mdiep** [comment]
Looks great! Thanks @dcaunt! I went ahead and published your draft.

I've been giving all the releases octopus names from [this list](https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=82595#null) (in alphabetical order). I added a name for the 2 newest releases.

**Comment by dcaunt** [comment]
Great, thanks!
